### ISSUE TITLE
Touch Navigation Issue

### ISSUE THREAD

**Issue by FrancisKunz** [sethchhim/Kuboo#1]
Hi,

Thanks for the nice job.

Seems like a strange behaviour but Kuboo can't turn page.
In fact, i can flip one page but the second page seems to be unresponsive to touch control.
I can navigate using the interface but i can't use the page flipping.

Hoipe this issue is clear enough for u

**Comment by sethchhim** [comment]
I tested on Android  6.0.1 and 8.0.1 which works fine. Please post your device and Android version and I will mock it in emulator.

**Comment by FrancisKunz** [comment]
Android 7.1.1 on a Samsung Galaxy A8 (2018)

I can touch my device to get navigation and book information but i can't slide the pages

thx

**Comment by sethchhim** [comment]
I have tried 7.1.1 on 1080x2220 with software navigation keys and the pages turn fine for me. I don't know what else to try except maybe do a clean reinstall of the app.

**Comment by FrancisKunz** [comment]
Tried something different.
Seems to work but i have to swipe only at the very bottom of the screen.

Thx

**Comment by sethchhim** [comment]
I found something similar. The page does not swipe unless it starts from towards the center, meaning edge swipes are not triggering the swipe. Thanks for the tip, I will investigate further.

**Comment by sethchhim** [comment]
Fixed a7d38954a2e05ba630a053352c6038a0b465ae9b
