### ISSUE TITLE
PDF format 

### ISSUE THREAD

**Issue by lbesnard** [sethchhim/Kuboo#14]
Hi

What an amazing software, thanks for all the work and improvements. 

It seems like PDF files are fully downloaded before being readable. They are not streamed like CBZ or CBR formats. Maybe this could be added as a feature request for a future version?

Cheers

**Comment by sethchhim** [comment]
I would love this feature too but the Ubooquity server only separates `COMIC BOOKS` for individual loading of pages. This feature needs to be implemented at the server level and is out of my control. Thanks for the feedback.

**Comment by lbesnard** [comment]
thank @sethchhim . This is weird as it was working in your previous software "vewier + for ubooquity".
Anyway, thanks again
