### ISSUE TITLE
Add in progress downloaded files to home screen.

### ISSUE THREAD

**Issue by ghostyroasty** [sethchhim/Kuboo#15]
I have downloaded a free comic files and started to read one, but it does not show on the home screen and I have to go to the downloaded screen to continue reading. Excellent job on the app!

**Comment by sethchhim** [comment]
This is intended behavior. I hope it is not too confusing. The home screen is for `REMOTE` books. The download screen is for `LOCAL` books. It got confusing when mixing them both so they are separated and hold independent saved progresses.

Thank you for the feedback. Please keep reporting any bugs or feature requests if you are interested.
