### ISSUE TITLE
No folders or books showing

### ISSUE THREAD

**Issue by luontokoodaus** [sethchhim/Kuboo#16]
I host my library on the internet at eg: https://mysite.com/library

I also use a username/password setup to prevent unauthorised access.

The app reports that it's connected to my server. However the library is empty in the app. What should I do to fix this?

**Comment by sethchhim** [comment]
Could you please try to add "/" to the end so the address looks like:

https://mysite.com/library/

If that doesn't work, set up a mock username for me and I will test it out this evening. Email sethchhim@gmail.com

**Comment by luontokoodaus** [comment]
Thanks.

Adding the subdomain www. and also the trailing forward slash "/" solved the problem.

You may want to suggest that in the app description. Great app. Wish I could view my comics and raw files too but hey this is good enough for now!
