### ISSUE TITLE
"recently" dont sync between devices

### ISSUE THREAD

**Issue by sethchhim** [sethchhim/Kuboo#18]
Forward from e-mail
```

I was testing the app and saw your email in the about page so i thought ill ask you a question.

Im using the app on 2 devices, both my phone and my tablet and my hope was to be able to start read something on one of them and seamlessly continue reading on either device but the "recently" dont sync between devices.

Is this something thats on the roadmap?

Server side bookmarks works in the app so i could browse to the comic and continue that way but that is not the "seamlessly" im looking for, ;)
```

**Comment by sethchhim** [comment]
"Recently Viewed" is only saved locally because the Ubooquity server does not support it. I think this feature has been requested but has not yet been added. I have no control over this, sorry.

https://ubooquity.userecho.com/communities/1/topics/581-user-data-stored-on-server-recent-files-last-reading-position-readunread-favorites-tags

**Comment by DarkShadowSwE** [comment]
Ye, and the current state of "/user-api/bookmark" isnt of much use to achieve that either at the moment. 

Replyed to Tom and hoping for some feedback from him: https://ubooquity.userecho.com/communities/1/topics/499-expose-server-bookmarks-via-opds#comment-3908
