### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by sethchhim** [sethchhim/Kuboo#20]
Is anyone interested in helping me translate the app into your preferred language? 

All the strings are located at https://github.com/sethchhim/Kuboo/blob/master/app/src/main/res/values/strings.xml

I will provide more detailed instructions if there is any interest.

**Comment by FrancisKunz** [comment]
Hi,

ASAP, I'm gonna deal with french translation.

Thx for the job

**Comment by sethchhim** [comment]
@FrancisKunz I created the french fork at https://github.com/sethchhim/Kuboo/blob/translation_french/app/src/main/res/values-fr/strings.xml

1. Open the strings.xml link above and click the edit icon on top right (looks like a pencil)
2. Replace English Text with French Text
- ignore special characters like `\n` or `%1$s`
- if there is an extra `SPACE`, please keep it like that
3. Propose file change

Merci

**Comment by Skyline2k** [comment]
@sethchhim I'm a git noob, how do I create a german fork like you did?

**Comment by sethchhim** [comment]
@Skyline2k german fork
https://github.com/sethchhim/Kuboo/blob/translation_german/app/src/main/res/values-de/strings.xml

**Comment by sethchhim** [comment]
@FrancisKunz @Skyline2k Closing this request because I intend to implement [Poeditor](https://poeditor.com/) service. Forking custom xml files is not ideal for collaboration. Here is a preview of the process https://www.youtube.com/watch?v=vCijUahRgKo

I will open a new thread, thanks for your help.
