### ISSUE TITLE
F-Droid Store

### ISSUE THREAD

**Issue by WisdomCode** [sethchhim/Kuboo#23]
First of all, thanks for all effort, this is an awesome app, I've been looking for this for some time.
As this project is open source, I'd like to propose to add it to F-Droid. 
The process is described [here](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md).

Also, just as a thought, maybe an option for displaying all comics at once in the 'browsing' tab regardless of Folder structure would be nice.

**Comment by sethchhim** [comment]
`As this project is open source, I'd like to propose to add it to F-Droid.`

I might add it when they finish up their [Repomaker](https://f-droid.org/en/repomaker/) tool. I see this warning for now:

```
Warning

This tool is still under heavy development.
Don't use it in production, yet!
Database migrations are not yet supported, use purge.sh to purge your data
and start from scratch after each update.
```
`Also, just as a thought, maybe an option for displaying all comics at once in the 'browsing' tab regardless of Folder structure would be nice.`

The app correctly reflects the OPDS feed that the server provides. If you are referring to `pagination`, it can be adjusted in the server to show more per page.

![untitled3](https://user-images.githubusercontent.com/11790350/43647159-cee9f80a-9704-11e8-91c7-dd7a4aa29910.jpg)

Thank you for checking out my app and providing feedback, it helps.
