### ISSUE TITLE
Chapterization access

### ISSUE THREAD

**Issue by WisdomCode** [sethchhim/Kuboo#25]
The Comicrack standard for metadata in cbz/cbr files allows the chapterization of comicfiles. I am not sure whether this is actually taken over by the ubooquity server (I could not find any documentation on that), but if it is, it would be a nice feature to jump between chapters in the client.

**Comment by sethchhim** [comment]
I do not know about this chapterization standard. Do you have any documentation I could follow or an example?

I assume this extra metadata is included in a separate file within the archive. If this is the case, I can add it for `LOCAL` books that have been downloaded. `REMOTE` books would not support this unless you could have the Ubooquity server "serve" this metadata through some new api.

**Comment by WisdomCode** [comment]
You can attach 'bookmarks' to any page of a cbz/cbr comic. This is done with the comicinfo.xml you may be familiar with, it is used for storing the comicrack metadata.
For a pretty good, although not official documentation, you can look [here](https://github.com/ciromattia/kcc/wiki/ComicRack-metadata). 

It would be interesting for local as well as for remote, the only source of information for the files you can access is the feed of the server, correct? In that case, I will maybe open a request in the ubooquity forum for adding this into the feed somehow.
Thank you anyway for considering this option!

**Comment by WisdomCode** [comment]
I am afraid I cannot find the official documentation right now, there is none at all afaik. The wiki is also not official, but simply a possible example without all possibilities. Those examples are valid.

However, the standard goes further, as shown by the link I provided you as well as some Comicreaders that support bookmarks following the Comicrack standard. On android, their [official app](https://play.google.com/store/apps/details?id=com.cyo.comicrack.viewer.free&hl=en_US) does this for example.
Comicracks web presence seems to be broken in many ways, so some links that should provide information are either dead or useless. Nevertheless, the 
[kcc wik page](https://github.com/ciromattia/kcc/wiki/ComicRack-metadata) 
does show in an accurate and easy way how it should look like.
If you (or anyone else) find an official documentation, I'd be glad to see it. Until then, if you don't believe the kcc documentation, download the comicrack app, add some rows like demonstrated by kcc to a cbz/cbr, load it into the app, tap once in the middle of the screen. On the left side, you can see a symbol that resembles a page with lines on it. Tapping on it will show you the chapters and the thumbnail of the related page. You can switch between them with a tap.

**Comment by sethchhim** [comment]
@WisdomCode Ok your link was helpful. I will try to write it when I have time.

```
<?xml version="1.0" encoding="utf-8"?>
<ComicInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <Series>Dragon Ball</Series>
   <Volume>1</Volume>
   <Writer>Akira Toriyama</Writer>
   <ScanInformation>MCD(3106)</ScanInformation>
   <Pages>
      <Page Image="0" Bookmark="Cover"/>
      <Page Image="4" Bookmark="Table of Contents"/>
      <Page Image="6" Bookmark="Tale 1: Bloomers and the Monkey king"/>
      <Page Image="36" Bookmark="Tale 2: No Balls!"/>
      <Page Image="50" Bookmark="Tale 3: Sea Monkeys"/>
      <Page Image="64" Bookmark="Tale 4: They Call Him... the Turtle Hermit!"/>
      <Page Image="78" Bookmark="Tale 5: Oo! Oo! Oolong!"/>
      <Page Image="92" Bookmark="Tale 6: So Long, Oolong!"/>
      <Page Image="106" Bookmark="Tale 7: Yamcha and Pu'ar"/>
      <Page Image="120" Bookmark="Tale 8: One, Two, Yamcha-cha!"/>
      <Page Image="134" Bookmark="Tale 9: Dragon Balls in Danger"/>
      <Page Image="148" Bookmark="Tale 10: Onward to Fry-Pan"/>
      <Page Image="162" Bookmark="Tale 11: ...And into the Fire!"/>
      <Page Image="176" Bookmark="Title Page Gallery"/>
   </Pages>
</ComicInfo>
```

**Comment by WisdomCode** [comment]
Awesome, thank you!
I also requested the chapterization in the [ubooquity forum](https://ubooquity.userecho.com/communities/1/topics/688-feature-request-comicrack-bookmark-api)
If there is any progress on that, I will add it in this issue. If you need further help, I'll gladly assist.

**Comment by sethchhim** [comment]
@WisdomCode I wrote the feature you requested. It only applies to `LOCAL` books that contain the ComicInfo.xml file with bookmarks. Please feel free to re-open this issue if the Ubooquity server will support ComicInfo.xml bookmarks for `REMOTE` books in the future.

commit 195b88857c1b8415afabf76ffc08ef00f29eb858

![untitled3](https://user-images.githubusercontent.com/11790350/44364004-e1308000-a493-11e8-8899-e71e599bc81b.gif)

**Comment by WisdomCode** [comment]
Wow, that was quick! 
Thank you very much, looks perfect!
