### ISSUE TITLE
What URLs does Kuboo need?

### ISSUE THREAD

**Issue by Tailchakra** [sethchhim/Kuboo#26]
Amazing piece of software you've got here, except I've got ubooquity behind a reverse proxy with nginx auth, this allows me to have all my services unauthed behind 1 overall auth.

```
location /comics/ {
auth_request /auth-4;
proxy_pass http://192.168.2.20:2202/comics/;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
add_header Vary “Accept-Encoding”;
add_header Access-Control-Allow-Origin *;
proxy_read_timeout 1800;
proxy_connect_timeout 1800;
proxy_request_buffering off;
proxy_buffering off;

location /comics/opds-comics/ {
	auth_request off;
	proxy_pass http://192.168.2.20:2202/comics/opds-comics/;
}

}

```

This allows me to have that auth and have /opds-comics/ "auth-less" (for lack of better words). Everything works except for that it can't reach the bookmarks. Therefor my question is this:

What are all the URLs that Kuboo needs so I can turn auth off for those particular URLs (Like bookmarks)

**Comment by sethchhim** [comment]
URL for bookmark api

`/user-api/bookmark?isBook=false&docId=<COMIC_ID>`

**Comment by Tailchakra** [comment]
Mmh, I'll set up something for you in a while. Won't be home most of the rest of the week, so I'll have something next week around monday/tuesday.

The having to need a user does indeed affect what I want to achieve. I don't want my users to have the need to login again once they are already logged into the site, as is how I hoped Kuboo had a local cookies bookmark like Ubooquity has on the webclient. (My users never ever use the site, they use it solely through apps)

I'll mail you a mock server next week including what I want to achieve and why! On the road as we speak so I'm not really explaining it the best way possible haha.

--

I'm still trying to figure out how I want to do it myself, if only ubooquity had either registration or ldap - that would fix the entire issue

**Comment by sethchhim** [comment]
` I don't want my users to have the need to login again once they are already logged into the site, as is how I hoped Kuboo had a local cookies bookmark like Ubooquity has on the webclient.`

Kuboo does use local bookmarks as default and then pulls from the remote api. If the remote pull is successful, it should update the local bookmark.

If you want your users to only use local bookmarks, I can implement:
- a settings toggle to prevent all remote api requests.
- a checkmark on server page to indicate reverse proxy to prevent all remote api requests

This is just a thought, look forward to your opinion when you have time.

**Comment by Tailchakra** [comment]
Mmh, that would definitely make things a lot easier. There's problably a tons cleaner solution to the need that I have, but a settings toggle to prevent remote api bookmarks would do the trick. I'd just have my users download Kuboo, have them insert https://www.domain.tld/comics/opds-comics and boom everything works. Having my ubooquity behind a reverse proxy like that makes opening comics impossible due to the bookmark api throttle.

That is though, if it's not too much of a "dirty" solution for you.

**Comment by sethchhim** [comment]
I have been thinking about this issue and wonder why doesn't the proxy relay the bookmark api requests. I believe it should work fine. You are right, the suggested solution I recommended is lazy. I would still like to test your mock setup myself and dig deeper.

**Comment by Tailchakra** [comment]
Weeelllll, I've screamed too early.
Sorry for bothering you with this without trying things myself, haha! I did have to know the URL though, but apparently giving `192.168.2.20:2202/comics/user-api/ > domain.tld/comics/user-api/` full access works straight away! So no need to do anything from your side haha!

If you want I can still give you my config though?

**Comment by sethchhim** [comment]
Ok nice work. No need to setup access for me since issue is resolved.
