### ISSUE TITLE
List mode issue view

### ISSUE THREAD

**Issue by Tailchakra** [sethchhim/Kuboo#30]
Hi again!

Is it possible to get list view instead of imageview during issue select? I've got various comics where I started years ago and want to continue now, except I can't tell which issue it is in Kuboo without selecting it first.

Maybe have the option to switch between image view and list view on the topright? (the three dots where it just says about now)

![screenshot_20180827-100810](https://user-images.githubusercontent.com/24505478/44648410-35ca8280-a9e1-11e8-9be1-302c1a4ef689.png)

**Comment by sethchhim** [comment]
Here is my first attempt. Let me know if you want anything changed.

![screenshot_1535399158](https://user-images.githubusercontent.com/11790350/44682054-51994d00-aa10-11e8-9192-72372c9a0b11.png)

**Comment by Tailchakra** [comment]
That's amazing! **Precisely** what I had in mind! You're quick on this 😃

**Comment by sethchhim** [comment]
This is off topic but I do not have any testers to ask. Did you upgrade to `1.0.9` and are able to connect to your server fine? A different user upgraded and is unable to connect but I am unable to recreate this problem. I have tested both emulators and real devices. I am starting to think this is a rare isolated incident or user error.

**Comment by Tailchakra** [comment]
Both my manga and comic ubooquity server connect with kuboo just fine. The only way I get "Server not available" is when I click "open series" for `btooom!` on my mangaserver, going to it through the list works fine, homepage "open series" gives me the error. `Preacher` on my comicserver works fine however. Odd.

**Comment by sethchhim** [comment]
I probably broke something. I think if you delete that bookmark and add a new one, the open series might work again.

**Comment by Tailchakra** [comment]
Correct, seems it was only on already open comics during the update. When reading those comics it also said page not found. Restarting the comic did the trick!

**Comment by sethchhim** [comment]
Thanks for your input, I let the user know.

New toggle looks good and is only visible when `MEDIA` folder is shown. 
commit e5ce678960eb8649e5241ce0c118b3f9222f390f
