### ISSUE TITLE
Hide read comics

### ISSUE THREAD

**Issue by exielo** [sethchhim/Kuboo#31]
Love the app!  Finally had to switch from comicrack and this app combined with ubooquity has been the only option that worked for me (I have tried close to 10 others). I appreciate all your work.

Is it possible to hide read books? It would help greatly with getting to the new issues of the series I frequently read.

**Comment by sethchhim** [comment]
Yes, this option could be made but only at the client level. Pagination would make it kind of ugly, let me explain.

Ubooquity can split items of a folder to separate pages, example would be a folder has 100 items but first page shows only 30 items and so on. For instance, the first 29 items are "finished" and hidden, then the client will show 1 item per paginated page. This is not a true "hide" of items and will result in multiple empty or incomplete pages possibly. I could try a custom solution but it can get ugly real fast.

My opinion would be to implement this at the server level (opds) so it would be reflected to all clients correctly.
