### ISSUE TITLE
Tracking and serie order

### ISSUE THREAD

**Issue by FrancisKunz** [sethchhim/Kuboo#35]
Hello,

when i enable the tracking function for a serie, sometimes Kuboo goes weird and download a random number of issues.
I recently find that only series with the title metatag have this problem. Maybe it's related to the field you're using to order the serie.

Hope you'll find a way,
Thank you for this awesome app

**Comment by sethchhim** [comment]
I rewrote a lot of the download tracking feature, are you on the latest version `1.1.0_v3` ?

`I recently find that only series with the title metatag have this problem. Maybe it's related to the field you're using to order the serie.`
I don't understand what this means. The sort order should be by the "id" number in the opds feed. I will look into it.

**Comment by sethchhim** [comment]
@FrancisKunz I am able to reproduce this issue now. I will work on a fix soon.

**Comment by FrancisKunz** [comment]
Thank you, it happens mostly on first issue, kuboo downlaod n°3 directly and then start downloading. So it goes to n°5 but i can't read (offline) issues n°1 and n°2

**Comment by sethchhim** [comment]
@FrancisKunz I uploaded the fix to the beta channel as `1.1.4_beta1`. You can opt-in the beta release through the play store app page or this link https://play.google.com/apps/testing/com.sethchhim.kuboo, and then update the app.

My testing shows correct behavior but I am afraid of any software regressions. If you give me the thumbs up, I will forward to the release channel.

**Comment by FrancisKunz** [comment]
Your fix seems ok.
I tried 10 series and everything is ok.
There is only one serie which still show some awkward behaviour but it might be due to bookmarks.
I'll keep you updated.

**Comment by sethchhim** [comment]
Feel free to close this it is solved
