### ISSUE TITLE
PDF > 100 Mb fails on loading asset

### ISSUE THREAD

**Issue by lbesnard** [sethchhim/Kuboo#37]
I've noticed that big PDF files (could be less than 100Mb by the way) fail to be 'streamed'. On the 'loading asset' part, kuboo just closes itself. This happens on two of my android devices with various PDF's. Although they work fine on the ubooquity web browser.

One feature to add would be to show a percentage progress on the loading asset part, so a user can see that something is actually happening.

If instead of 'streaming' a pdf, I decide to download the pdf comic via the app, then Kuboo behaves fine. (although still a bit slow with big pdfs)

**Comment by sethchhim** [comment]
fixed https://github.com/sethchhim/Kuboo/commit/0b31ddc30a0649b353c9a39637573abd1cf5311b
