### ISSUE TITLE
Books/Comics Server

### ISSUE THREAD

**Issue by distrax** [sethchhim/Kuboo#38]
Ability to load books and comics from the same server without switching server. At the moment it seems that it requires the server to either be opds-books or opds-comics. If this isn't the place for a feature suggestion please let me know and I'll withdraw the issue.

**Comment by sethchhim** [comment]
I think this would be a server feature. The app shows correctly what the server gives it. 

Yes this is where you can post features and bugs, keep them coming and I will try my best to respond.

**Comment by distrax** [comment]
Hmm. Ok. I can see that then. I will mention it to the ubooquity people then. Viewing the server directly from the homepage does show both books and comics.  Maybe allowing the application to show media from two(or more) servers at once would be a way to fix it from the application side. Thanks for the quick attention. Just fyi I think the application is great as is. I'm certainly not complaining.
