### ISSUE TITLE
Hide/Show in the download tab

### ISSUE THREAD

**Issue by FrancisKunz** [sethchhim/Kuboo#40]
Hello,

Do u think u can add the "hide fully read" in the download tab.

As an exemple : 
Batman is on my traking download list
I just finished batman 55 so nothing more to read
Kuboo hides it from the list
Batman 56 is out and i added it to ubooquity
Kuboo gets a new issue to download so Batman shows up in the list

Thank you for your time and devotion

**Comment by sethchhim** [comment]
commit 62ae1256e29711c8d4e0c2ccddfba33ff83f43ac

You can preview the feature in `1.1.4_beta2`. Let me know if it works for you.

**Comment by FrancisKunz** [comment]
Hello,
Seems to work very well. I'll keep u updated as soon as new issues are out.

**Comment by sethchhim** [comment]
This is how I tested:

1. Enable download tracking on a series
2. Disable network connection
3. Read all the books and it will hide
4. Enable network, Press Resume All, new books will download and it should show again

**Comment by FrancisKunz** [comment]
I tested it live by adding this week issues to let ubooquity server and it worked perfectly well.
Nice job
