### ISSUE TITLE
Random shuffle?

### ISSUE THREAD

**Issue by cartoonmonkey** [sethchhim/Kuboo#41]
Can you implement a random shuffle?

**Comment by sethchhim** [comment]
Interesting request but I think the use case is too rare considering most libraries are episodic in nature. If this is implemented in the server as a native feature I will be happy to incorporate it.

**Comment by cartoonmonkey** [comment]
I think it is in fact native to Ubooquity. It exists in the web interface as well.
![ubooquity](https://user-images.githubusercontent.com/2583963/46374141-d0ebf300-c644-11e8-9e63-6aa2c9f2b6b9.jpg)

**Comment by cartoonmonkey** [comment]
(I use it because, I have a rather large comics library, and I occasionally want to shuffle the selection, to see something new I might not have discovered by browsing A-Z.)
