### ISSUE TITLE
Reload comic cover

### ISSUE THREAD

**Issue by cesalo** [sethchhim/Kuboo#43]
The wrong comic was put in the wrong series. I fixed this but Kuboo keeps showing (In Recently viewed and whe I opened the series) the old cover. Ubooquity shows the correct cover after it re-scanned the directories.
Didn't know that Kuboo kept this in a different place - I assumed it was what Ubooquity had available.
How can I force Kuboo to reload the cover?

**Comment by sethchhim** [comment]
You can try to clear cache

![screenshot_20181010-185413](https://user-images.githubusercontent.com/11790350/46770674-519e9500-ccbe-11e8-827d-189a27ca6a55.jpg)

**Comment by cesalo** [comment]
Excellent .. That solved the issue.
