### ISSUE TITLE
tracking issue

### ISSUE THREAD

**Issue by FrancisKunz** [sethchhim/Kuboo#46]
Hi,

Just had a small problem with Kuboo, some tracked series won't update.

I waited for multiple auto-upadtes to happen, i tried to update manually, tried to toggle tracking on and off but nothing.

Whenever I erase the serie and re-track it, everything seems to work fine

I can give u some screenshots if u need

Thx

**Comment by sethchhim** [comment]
Do you use multiple servers? Tracking requires your active server to match the download item's server.

**Comment by FrancisKunz** [comment]
I only have one server and this issue just appeared recently with issues n°57

**Comment by sethchhim** [comment]
Please post app version.

**Comment by FrancisKunz** [comment]
Version 1.1.4_BETA3

**Comment by sethchhim** [comment]
I think this is the bug https://issuetracker.google.com/issues/115560696

You are probably using Workmanager 1.0.0-alpha08 which has this bug. I have uploaded a new version to the BETA channel which contains 1.0.0-alpha10, which contains the fix from 1.0.0-alpha09.

The app version which contains the fix is `Kuboo 1.1.4_beta4`. I just recently uploaded it so it may take a few hours to post. If the tracking unexpectedly stops working for no apparent reason, I'm pretty sure this is the fix. Please keep me updated.

**Comment by FrancisKunz** [comment]
The fix u pushed this nught didn't change anything but a complete re-install get the jib done for me.

**Comment by FrancisKunz** [comment]
Today, my new batch of comics just arrived and the same problem still occurs.

Last week was Batman, Today Flash, but issue 57 is not handled by Kuboo's tracking

**Comment by sethchhim** [comment]
I found a bug where periodic work load did not initiate but according to your problem even if you press "Resume All" manually it won't work?

Could you browse the opds feed and tell me if the issue 57 is in correct sequential order (at the end)? Just covering all possible issues.

**Comment by FrancisKunz** [comment]
I browsed the OPDS-feed and all this issues are in good place.

The "resume all" wasn't enabled, i cas clikin' but no answer.

I'll keep u updated with this week new batch

**Comment by sethchhim** [comment]
Ok sounds good, be sure to update to `1.1.4_beta5` for your test as it includes a download tracking fix.

**Comment by sethchhim** [comment]
I am getting weird errors with the automatic updates. Some times it deletes wrong ones and misses next issues. Just letting you know you aren't alone with this.

**Comment by FrancisKunz** [comment]
Ur last update seems to work better for me but still some issues but, mostly, the job is done quite nicely.

In the past week, i got only one pb : i added a new serie to my tracking. issues 1, 2, 3 and 4 were DLed. But when i updated my app, those issues were deleted to download issues 29, 30, 30 and 31.
I get that the issue 29 is a tie-in from another serie i already red. So maybe the bookmark has something to do with this kind of behaviour.

Hope it'll help.

PS: i'm still beta-testing, so i'll keep u updated if u push anything in beta

**Comment by sethchhim** [comment]
commit https://github.com/sethchhim/Kuboo/commit/d7e5f16f2dd33078327f13d1b21d6da2a9224c4b

I am confident this will fix it. I am able to consistently reproduce the bug and this solves it. Sorry it took so long, I'm working on another special project. Available on `1.1.5_beta1`, should be live shortly.

**Comment by sethchhim** [comment]
Looks like a bad upload, disregard it. I will try to fix soon.

**Comment by FrancisKunz** [comment]
thx, looking forward to see it

**Comment by sethchhim** [comment]
It is live `1.1.5_beta1v2`. Lets fix this annoying bug.
