### ISSUE TITLE
Some epubs are displayed as completely empty black screen

### ISSUE THREAD

**Issue by xerance** [sethchhim/Kuboo#47]
Hello, I'm having an issue with a few epub books, they dont seem to load up correctly?

Getting a complexity empty black screen while opening them, but they load just fine in web browser. 
As some loads up just fine, I'm assuming its not an issue with the server.

is this a known issue?

other than sending one of the epubs in question, i'm not sure what more info I can post.

also getting this one on a few: text works just fine, but image illustrations aren't loaded 
![screenshot_20181026-010025_kuboo](https://user-images.githubusercontent.com/16266200/47535196-b8c16980-d8ba-11e8-8d07-21fee219eff5.jpg)

phone: samsung galaxy s8 plus
kuboo version: 1.1.3
server version: Ubooquity 2.1.1

**Comment by sethchhim** [comment]
I am going to implement a brand new epub reader. The current one is a bare bones place holder as the app was built just for comics in the first place. I hope to make epubs a first class citizen but this is not trivial and takes time as I'm searching for better solutions.

You can still e-mail me the epub if you want me to check it out. sethchhim@gmail.com

**Comment by xerance** [comment]
Sounds good, will send you 2, one which is completely black and one whom the images doesn't load properly.

updated the main post abit.

**Comment by sethchhim** [comment]
I see the images, this is a known issue and will not be fixed because I intend to replace the entire epub reader in the future.
