### ISSUE TITLE
Hide recently viewed

### ISSUE THREAD

**Issue by FrancisKunz** [sethchhim/Kuboo#48]
Hi,

As i'm "Tracking n°1 Fan", the recently viewed is totally useless to me. 

Can u add a third home screen setup : 
- Recently Viewed only
- Recently Viewed + Recently Added
-Recently Added only

Maybe it'll be possible to use to download screen as the application startup screen

Thanks for the job

**Comment by sethchhim** [comment]
I like the idea to be able to change starting screen.

**Comment by sethchhim** [comment]
commit f82aa0cbac21dcec32bc14e01c94720a51612d8f

I added the feature to `Settings`, it is called `Start Tab`. You can check it out on `1.1.4_beta5`.
