### ISSUE TITLE
Kuboo not working

### ISSUE THREAD

**Issue by tomtom602** [sethchhim/Kuboo#49]
Hi
I cant seem to get Kuboo to work. 
Ubooquity is working fine
Opds feed is activate
But when I put my server IP adresse in ubooquity, the 3 dots appears but noyhing else happen. 
What am I doing wtrong ?

My server is on a freenas. I have installed version 2.1.2 of ubooquity

**Comment by sethchhim** [comment]
@tomtom602 

Please show your server format, the app is very picky, you need to include the trailing "/" character if it is missing.

To verify the opds feed is working just try it in a browser and see if the xml data shows up.

Correct format:
"http://192.168.0.1:2202/opds-comics/"

**Comment by tomtom602** [comment]
I have already have read about that in another thread.
My server is set as :
http://192.168.0.5:2202/opds-comics/

**Comment by sethchhim** [comment]
```
Another thing
My library is pretty big: more than a thousand comics. Could it be that?
```
No, this does not matter.

Just to cover everything, please post app version and if you checked via the web browser if you can pull the xml feed.

**Comment by tomtom602** [comment]
I have already checked throug browser and the xml appear correctly
The app version is 1.1.5

I have tried with another app : challenger.
It connects to the server, I can go to the list of folders but it seem to be a problem to open /download comics.. It could be related.

**Comment by sethchhim** [comment]
Please verify you are checking on the client device's web browser and not the server's web browser.

**Comment by tomtom602** [comment]
Yes, my server doesn't have a web browser anyway.
I have checked with my desktop and with my mobile and I see the xml with both devices.

**Comment by tomtom602** [comment]
Well..
I have just tried Kuboo this morning again, and now it's working... 
I really don't understand.. Was there a new release of the app?

**Comment by sethchhim** [comment]
Nothing has changed but I'm glad it is working for you. Let me know of anymore issues.

**Comment by sethchhim** [comment]
I can't comment because I might give poor advice considering this is outside the app. Although I would appreciate it if you posted a solution if you found one. I am currently building my own server and would appreciate any pitfalls I could avoid. Thanks and good luck.

**Comment by tomtom602** [comment]
Thank you, will do.
I have asked the question on ubooquity forum. Still waiting for an answer.
