### ISSUE TITLE
Series Navigation

### ISSUE THREAD

**Issue by FrancisKunz** [sethchhim/Kuboo#5]
Hi, me again ;-p

I think you can improve series navigation by adding the "OPEN SERIE" button within the info panel of the reader. The downloaded items aren't always recent item so we need another way to go directly to the serie.

Once again : thx for the amazing job 🥇

**Comment by FrancisKunz** [comment]
I got an issue with download tracking  (i'll make a dedicated post with a short video of the issue).

What i mean is : i'd like to be able to go directly from the reader to the serie folder. Sometimes when i read in strict order, i get that i need to go to another issue (e.g. : annuals/ see issue #xx/ DC #0 month...) and the "open serie" button on the info panel would be a nice addition IMO.

**Comment by sethchhim** [comment]
Fix 2ffc52de902324e282e8004c0ab253e72fdb7ac2

Please note `Open Series` will only be available if the `Active Server` matches that of the `Book`.
