### ISSUE TITLE
 Ability to view pages separately

### ISSUE THREAD

**Issue by grandsword** [sethchhim/Kuboo#50]
When two pages are in one file, I want to divide the pages and view them one page at a time. plz~!

**Comment by sethchhim** [comment]
Please clarify what you mean by this because I do not understand.

Do you want to:
-Split a single image into two images
-Split an archive file into multiple archive files

What is your use case?

**Comment by grandsword** [comment]
Split a single image into two images.

thank you

**Comment by sethchhim** [comment]
This type of media manipulation should be done on the server so thin clients don't have to process.
