### ISSUE TITLE
OutOfMemoryError while reading downloaded comic

### ISSUE THREAD

**Issue by lbesnard** [sethchhim/Kuboo#52]
I would like to re-open this https://github.com/sethchhim/Kuboo/issues/39 as I have exactly the same issues.
I usually have to exit the comic and re-open it as swiping rarely works.
I'm using the latest version. 
![screenshot_2018-12-21-08-38-22](https://user-images.githubusercontent.com/2382814/50317697-051ed380-0511-11e9-9c0c-1755a851bdc9.png)
![screenshot_2018-12-21-08-33-50](https://user-images.githubusercontent.com/2382814/50317698-051ed380-0511-11e9-990d-808ce6005a6a.png)
![screenshot_2018-12-21-08-26-52](https://user-images.githubusercontent.com/2382814/50317699-05b76a00-0511-11e9-8b2e-a0e5a609c0cb.png)

**Comment by sethchhim** [comment]
Is this a downloaded local file or remote pull?

**Comment by lbesnard** [comment]
It is a file downloaded locally via the app. Streaming works fine. Does it answer your question ?

**Comment by lbesnard** [comment]
Thanks a lot ! will give it a crack. Sorry for the late response, I was away.

**Comment by sethchhim** [comment]
Ok, I moved that setting to `Settings -> Advanced -> Force Downsizing`
