### ISSUE TITLE
Dumb Question

### ISSUE THREAD

**Issue by carbonbaseunit** [sethchhim/Kuboo#55]
How do I log in?   username password?

**Comment by sethchhim** [comment]
If you are testing out the alpha, try 
username: `1`
password: `1`

I closed the thread because I think its too early to release even as an alpha build. https://github.com/sethchhim/Kuboo/issues/54

**Comment by carbonbaseunit** [comment]
Ha!  See... Dumb question. Thanks

**Comment by sethchhim** [comment]
Let me know if you get it up and running. My first feedback was unable to install. :(

**Comment by carbonbaseunit** [comment]
It's up.  It's pretty simple.  install Java, run the software.  Go to http://xxx.xxx.xxx.xxx:8080.  Would be nice to be able to change the port.
