### ISSUE TITLE
Home layout weird on 18:9 phones

### ISSUE THREAD

**Issue by alfablac** [sethchhim/Kuboo#56]
Home layout on 1.1.8 looks weird on my 18:9 Xiaomi phone (1080x2160).
Recently viewed only shows about a quarter of a big cover. I have to slide through the screen to see other options.
I guess it's due to this strange resolution. Maybe a custom setting to fix this (Better than treating every resolution, I dunno).

**Comment by sethchhim** [comment]
Was the previous size ok for you? If so I will revert and add an "offset" option instead of hardcoding it.

**Comment by sethchhim** [comment]
fixed cc2026a189fa540a9968051ea264cc0a72aab229

You can find the new setting at `Settings -> Advanced -> Recently Viewed Height Offset`. The larger the percentage you set, the larger the Recently Viewed item will be, so it might take some experimentation to get it right. 

I have uploaded version 1.1.9 to the BETA channel. If you give me the thumbs up, I will push it to the release channel.

**Comment by alfablac** [comment]
I couldn't install the -release one (it fails to install.. no idea why) so I tried the -debug package and it installed.
The changes worked great for me. I was getting a huge cover in the home screen lol
The old layout was ok, but the custom setting feels better IMO.

Thanks for responding to the issue so fast!
