### ISSUE TITLE
Folder is empty! Error

### ISSUE THREAD

**Issue by fdcardano** [sethchhim/Kuboo#57]
Hi Seth, 

I'm having an issue where Kuboo connects to my server but does not show any comics. I can access the server fine through ubooquitys web client, and the error message is different to when kuboo can't connect to the server (where it says server not available) -- in this case it says start reading to add items under the recent comics heading. When I choose more, I get a 'folder is empty' message. 

Any idea what I've done wrong?

**Comment by sethchhim** [comment]
Please post the exact url format you are using:

"http://192.168.0.1:2202/opds-comics/" 

A common error is the url requires the last character of "/"

**Comment by fdcardano** [comment]
Hi Seth, thank you for the reply. When I hit Browse, I also get folder is empty.

**Comment by fdcardano** [comment]
http://192.168.1.x:2202/opds-comics/ -- just quadruple checked, definitely using the correct url afaik.

**Comment by sethchhim** [comment]
Try on a web browser to visit the url you are using. It should show an xml feed. Also, please note that opds feeds are disabled by default, I'm not sure why. You need to go to the server admin settings and enable it.

**Comment by sethchhim** [comment]
It should look like this:

![untitled](https://user-images.githubusercontent.com/11790350/51144744-f7aeed80-181f-11e9-8c12-20ecb39d61e4.jpg)

**Comment by fdcardano** [comment]
Hi Seth, works on both my browsers, pc and mobile. Not sure where to go from here.

**Comment by fdcardano** [comment]
`<feed xml:lang="en">
<id>
780a6725b1cc433fa296a4b8b17563ac-comicsLocalRootDirectory
</id>
<title>Comics shared directories</title>
<updated>2019-01-14T19:39:38+07:00</updated>
<icon>/theme/favicon.ico</icon>
<author>
<name>Ubooquity server</name>
<uri>http://vaemendis.net/ubooquity</uri>
</author>
<link type="application/atom+xml; profile=opds-catalog; kind=navigation" rel="self" href="/opds-comics/all?groupByFolder=true"/>
<link type="application/atom+xml; profile=opds-catalog; kind=navigation" rel="start" href="/opds-comics/"/>
<entry>
<title>Comics</title>
<id>1</id>
<updated>2019-01-14T19:14:17+07:00</updated>
<content type="html"/>
<link type="application/atom+xml; profile=opds-catalog; kind=navigation" rel="subsection" href="/opds-comics/1/"/>
</entry>
</feed>` 

This is the output I get - so there is one entry, is that right?

**Comment by sethchhim** [comment]
![untitled](https://user-images.githubusercontent.com/11790350/51145691-a2281000-1822-11e9-8f10-1d7ca4ce347f.jpg)

I highlighted an example of an entry. Post the full text, I think you only showed partial.

**Comment by sethchhim** [comment]
Ok I see your screenshot, the server looks good. Let me think about it.

**Comment by fdcardano** [comment]
Ok, great. Thanks so much for your help!

**Comment by sethchhim** [comment]
No bother, post any issues you have.
