### ISSUE TITLE
Text Sizes on Larger Resolution Devices

### ISSUE THREAD

**Issue by Clearmist** [sethchhim/Kuboo#59]
Some of the best devices for reading comic books include 10 inch and up devices. These include the Samsung Tab Pro S and Note Pro from 2014 and 2016. These have resolutions in excess of 2,400 pixels on their longest side.

On larger resolution screens with larger real estate Kuboo text sizes and icons need to be enlarged. Here are some samples of Kuboo running on a 12.3" diagonal 2K WLED with a resolution of 2400 x 1600. I have left the images full-size to give better perspective.

![screenshot 2019-01-23 at 11 03 30 pm](https://user-images.githubusercontent.com/4317724/51661490-db205d00-1f65-11e9-957b-801da5604667.png)

![screenshot 2019-01-23 at 11 03 25 pm](https://user-images.githubusercontent.com/4317724/51661489-db205d00-1f65-11e9-8564-ebacdba5315a.png)

![screenshot 2019-01-23 at 11 07 02 pm](https://user-images.githubusercontent.com/4317724/51661491-db205d00-1f65-11e9-9b08-1354171e6fe1.png)

Notice the small fonts I've highlighted yellow and the small icons I've highlighted orange.

I have seen reference to SetTextSize() within your code, but seeing as how you're programming in Kotlin and I'm coming from the CSS world I wouldn't be able to figure out how to increase the font and icon sizes for a pull request faster than you'd be able. :)

**Comment by sethchhim** [comment]
I don't think this is critical but I will put it on the agenda for 2.0. Thanks for the concise issue, it was very clear.

Here is my roadmap:

1. Kuboo Backend Server 1.0 Release
2. Kuboo Android compatability layer with Kuboo Server
3. Kuboo Android epub/pdf rewrite (2.0)
4. Kuboo Android ui overhaul (2.0)

**Comment by sethchhim** [comment]
I am checking out high res layouts and comparing my app with Google apps on a 2000x3000 emulator. Icons and text look very similar. I want to adhere close to the material design spec. I don't think any action needs to taken regarding size. I do see some bugs I will try to iron out, like that seekbar is too wide.

**Comment by Clearmist** [comment]
Do you mean that the icons and text look similar to my sample screenshots?

On my large 12" screen you can see the text is quite small compared to the amount of space on the screen. If you're okay leaving the font-size the way it is would you consider adding an overriding default font-size option in the options menu?

**Comment by sethchhim** [comment]
Compare my app to something like the official Youtube app. The behavior is the same which is desirable for me. There are so many resolutions for Android, to stay sane we need to follow some standard. I don't have chromeos but there is an option in android where you can change global font size. I bumped it up and it looks much better, maybe you could try that if there is an option.

![screenshot_1548536673](https://user-images.githubusercontent.com/11790350/51792799-adfdc580-2184-11e9-827d-2e6b7a211af5.jpg)

**Comment by Clearmist** [comment]
Ah, that makes a lot of sense. I will use the native Android/ChromeOS settings to increase the font size. Thank you for helping me look into this issue.
