### ISSUE TITLE
[Feature Request] Story Arc Reading orders

### ISSUE THREAD

**Issue by icebal** [sethchhim/Kuboo#6]
It would be sweet to have a reading order function, either tying into mylar/comicvine, or to http://www.readingorders.com/

Not sure if this is out of scope for this project, and should maybe put on ubooquity?

**Comment by sethchhim** [comment]
Cool feature but this should be done on the server level or just manually by ordering files/filenames. I looked into something like this before but to pull metadata for individual comics. I think data like this should fall on the server to pull and persist for every client to retrieve.

Thanks for the input and interest in my app, keep the bugs or feature requests coming.

**Comment by icebal** [comment]
Sweet, ill do a request for ubooquity then, thanks for all your hard
work!!!!
