### ISSUE TITLE
ASAR Archive Support in Kuboo Server 1.0

### ISSUE THREAD

**Issue by Clearmist** [sethchhim/Kuboo#61]
Hi Seth, I'd like to talk to you about including ASAR archive support in your upcoming Kuboo Server. I wrote a bench marking app to compare random seek time between 7z, zip, and asar. I also made some graphs and found some Java based implementations of this very simple format.

Adopting asar support would greatly increase both scanning and page access times. If you're interested I'll keep this temporary email address open for a few days so we can exchange contact information and I can show you what I've found. sayda42@noifeelings.com

As a sneak preview here's a quick chart showing the processing time, in milliseconds, to seek 8 random files from a 24 jpg image archive. The sample size is 5.
![2019-01-26 08_22_34-window](https://user-images.githubusercontent.com/4317724/51789947-b84b9f80-2143-11e9-89b2-844387fd0e8e.png)

**Comment by sethchhim** [comment]
Here is a java implementation https://github.com/natanbc/asar

E-mail me a test archive and I will try it out. Sounds promising.

sethchhim@gmail.com
