### ISSUE TITLE
Right to Left double page navigation

### ISSUE THREAD

**Issue by gotson** [sethchhim/Kuboo#62]
I have some mangas (right to left reading order) composed of double pages scans, and i'm trying to read in half pages.

I set Kuboo in `Aspect Fill` so that only 1 of the 2 pages is shown at a time, and I set the reading order to RTL.

However there's some issues when navigating:

- touching the right part of the screen goes to the next double page, but shows the left hand side of the double page, instead of the right hand side
- horizontal scrolling from the right hand side of the page moves well to the left hand side. If going to the next page, same problem, it starts showing the left hand side of the page.

Basically at the moment:

- LTR reading with double pages is doable using scroll only
- RTL reading with double pages is impossible, you need to scroll back at every double page to see the first part

Ideally the best navigation would be to have something like Comicrack Android has:

- when you switch to RTL reading order, the controls are reverse: touching left goes forward, touching right goes backward. This removes confusion to the reader.
- when moving to the next double page, start by showing the page in full, then zoom on the part that makes sense depending on the reading order (right side for RTL, left side for LTR)
- have a consistent action for border touch controls: moving forward. If on a double page, scroll to the second part, or if already on the second part, go to next page.

**Comment by sethchhim** [comment]
Fixes are live in `1.2` on the beta channel.

**Comment by gotson** [comment]
Thanks, it fixes some of the issues, but touching the left side of the screen will only move to the next double page, and not scroll to the second part. That means navigation can only be achieved using scrolling, and not using touch or volume keys.

**Comment by sethchhim** [comment]
Coffee, black, lets do this.

**Comment by gotson** [comment]
one more thing i noticed is that when arriving on a double page, it shows the section that was last shown. To ensure proper navigation, it should take into account where you are coming from.

So if browsing forward, it should show the right part in RTL (and left in LTR), but when browsing backward, it should show the left part in RTL (and right in LTR).

Normally that should not happen with the current behaviour, as one will always move to the second part of the double page before going to the next page, so when moving back it should show the last part shown, which was the second part.

Hope that's not too confusing ! 😅

**Comment by sethchhim** [comment]
> So if browsing forward, it should show the right part in RTL (and left in LTR), but when browsing backward, it should show the left part in RTL (and right in LTR).

Could you check if this is fixed, should be in the beta. Might not affect recycled fragments but immediate left and right are working.

commit https://github.com/sethchhim/Kuboo/commit/a2d89dae3453e93722fc0be33562cb324c67e742

**Comment by sethchhim** [comment]
First draft of new feature available in `1.2.1` on the beta channel after Google approves it. That's all the time I have today, feedback is welcome.

**Comment by sethchhim** [comment]
> So if browsing forward, it should show the right part in RTL (and left in LTR), but when browsing backward, it should show the left part in RTL (and right in LTR).

I am able to recreate this issue. My earlier fix is not robust enough.

**Comment by gotson** [comment]
it's working, but now i'm not too sure if the different fit/fill options are making sense for double page.

Using `aspect fill`, it's filling the vertical, but given the ratios it doesn't display exactly half of a double page, but a little less. So when touching to go next, it will go maybe to the 2/3 of the page, and one more touch will go the last part.

Ideally we would need to have a double page display mode where it fills the viewport width with half of the page, in vertical mode. That would work for comics that are fully double page, but not when there is only a few in the book though. Somehow Comicrack managed this seamlessly, i'm not sure how they did that 🤔

I also noticed another potential bug, when using the existing double page mode (which switches to horizontal) and `aspect fit`, i can only scroll or touch to the right (whatever RTL or LTR).

**Comment by sethchhim** [comment]
> Using aspect fill, it's filling the vertical, but given the ratios it doesn't display exactly half of a double page, but a little less. So when touching to go next, it will go maybe to the 2/3 of the page, and one more touch will go the last part.

Hard coded a 12% negative offset, probably will make a setting in the advanced section.

> Ideally we would need to have a double page display mode where it fills the viewport width with half of the page, in vertical mode. That would work for comics that are fully double page, but not when there is only a few in the book though. Somehow Comicrack managed this seamlessly, i'm not sure how they did that 🤔

This is just my implementation, I have no plans to rewrite it, only fix bugs. If this is critical, I am happy to review pull requests.

> I also noticed another potential bug, when using the existing double page mode (which switches to horizontal) and aspect fit, i can only scroll or touch to the right (whatever RTL or LTR).

I am unable to recreate this issue.

**Comment by sethchhim** [comment]
> I also noticed another potential bug, when using the existing double page mode (which switches to horizontal) and aspect fit, i can only scroll or touch to the right (whatever RTL or LTR).

I am able to recreate this now.

**Comment by sethchhim** [comment]
> Using aspect fill, it's filling the vertical, but given the ratios it doesn't display exactly half of a double page, but a little less. So when touching to go next, it will go maybe to the 2/3 of the page, and one more touch will go the last part.

fixed https://github.com/sethchhim/Kuboo/commit/7fe9a1d5fcdedd45b28c3bb023588315deb9ed4e

> I also noticed another potential bug, when using the existing double page mode (which switches to horizontal) and aspect fit, i can only scroll or touch to the right (whatever RTL or LTR).

fixed https://github.com/sethchhim/Kuboo/commit/b254cade2f2eb6e19a4d1999de16a7c013ad2103
