### ISSUE TITLE
Loading Bookmarks on Open new comic 

### ISSUE THREAD

**Issue by Pahiro** [sethchhim/Kuboo#69]
Seems that, for some reason, it continues to wait for a response from the server on the bookmarks. 

When a bookmark is found it's basically instantaneous. 

When there's none, I get stuck on a "Loading Bookmarks" screen. To get around this I click "cancel" and then go into the comic again.

**Comment by sethchhim** [comment]
Thanks for the report.

Can you repeat this behavior for other series? I just reset my test server so it has no bookmarks but it is working correctly for me.

Here is the example url if you require any special setup on your server's end:
`http://192.168.1.1:2202/user-api/bookmark?isBook=true&docId={ID}`

I did a code review and found a missing error catch. This would only explain a corrupt bookmark, not an unread book, but it is worth a try. See commit https://github.com/sethchhim/Kuboo/commit/6ee0ac62e9ad41abf31b953dbd56ce9d47f7bd07. You can test this fix in about an hour, it is uploaded to the Play Store BETA channel for version `1.2.10`.

**Comment by Pahiro** [comment]
Yup, I was able to repeat the problem on every new comic. Once I used the work-around and a proper bookmark was stored they load immediately.

Unfortunately won't be able to test the fix today ("Load Shedding" in South Africa so I switched off my server for the day). Suspect it has something to do with my unique URL situation, IE. https://comics.mysite.com/

I'll send you the access details tomorrow for testing if it's not resolved with this fix.

**Comment by Pahiro** [comment]
Seems it's got something to do with my wifi. Testing it on a different wifi and I couldn't replicate the issue.

**Comment by sethchhim** [comment]
Please update if you find the root of this issue. I'm guessing some type of firewall or filter.

**Comment by Pahiro** [comment]
Very difficult to tell as the api is fully accessible through the PC. In this case I'm thinking more the proxy and dns bouncing the route incorrectly for some reason and just timing out eventually.
