### ISSUE TITLE
[Feature request] Library redesign

### ISSUE THREAD

**Issue by Anvirol** [sethchhim/Kuboo#70]
Main issue I've got with Kuboo is how content is currently organized and displayed.
Here's some things that could use changes.

**Browser** feature suggestions
- Show content in grid/cover/poster wall mode
- Support displaying "never read, recently added, recently read, in progress" etc.
- Manage content in bulk. e.g. select several folders and mark as read

This is what Kuboo (latest version from Play store) browse page looks like:
<img src="https://user-images.githubusercontent.com/3955313/52562399-13011e80-2e07-11e9-961c-35c201925c2c.png" width="480">

**Newly added** page feature suggestions
- Move to Browser or allow choosing as default for home view
- Show content per folder
- Display series/chapter name (there's a lot of content without series title and chapter number clearly displayed in cover page)

Newly added 
<img src="https://user-images.githubusercontent.com/3955313/52562143-2495f680-2e06-11e9-9435-4e9b84f7bd70.png" width="480">

Here's how content is organized and displayed in Cover - Comic Reader (Windows UWP)
- it can display: recently added, never read, recently read, etc..
- content is displayed in folders (better way IMO)
<img src="https://user-images.githubusercontent.com/3955313/52561608-953c1380-2e04-11e9-9788-b1968f105d8e.png" width="480">

Recently added in Comicrack for Windows. As you can see, there's many filters to choose from. 
<img src="https://user-images.githubusercontent.com/3955313/52560252-66bc3980-2e00-11e9-94c8-58563caad8a3.png" width="480">

Never read:
<img src="https://user-images.githubusercontent.com/3955313/52560296-953a1480-2e00-11e9-8fbf-7857707d3971.png" width="480">

**Comment by sethchhim** [comment]
Ubooquity opds folder list does not support cover images. The thumbnail and badge you see is a hack I had to workaround for immediate children folders. I've thought about this and if I wanted to write it, it would make multiple network requests for every folder to get a single cover image. This is not ideal and would affect performance greatly.

If you could take a moment to look at the opds api you can see how bare-bones it is. There is no filtering option available to developers. I could also do this with a hack, but it is again not efficient enough especially considering multiple paginated pages. If this reflects poorly on my app, so be it, but I do not control both server and client. I don't blame Ubooquity as this setup gets the job done for me personally.

Please feel free to reopen the issue or submit a pull request if I am mistaken.

**Comment by Anvirol** [comment]
> 
> 
> Ubooquity opds folder list does not support cover images. The thumbnail and badge you see is a hack I had to workaround for immediate children folders. I've thought about this and if I wanted to write it, it would make multiple network requests for every folder to get a single cover image. This is not ideal and would affect performance greatly.
> 
> If you could take a moment to look at the opds api you can see how bare-bones it is. There is no filtering option available to developers. I could also do this with a hack, but it is again not efficient enough especially considering multiple paginated pages. If this reflects poorly on my app, so be it, but I do not control both server and client. I don't blame Ubooquity as this setup gets the job done for me personally.
> 
> Please feel free to reopen the issue or submit a pull request if I am mistaken.

Thanks for taking time to reply anyway 👍 

A lot of Comicrack users have been looking for alternative solutions to reach same feature level, since that project has been abandoned. I'll keep hoping that some year Ubooquity and clients will evolve enough.

**Comment by sethchhim** [comment]
I agree with you so I'm experimenting with backend and web development. There is an alpha build on my attempt at a server in the Releases section of this github. Please take into account I am learning along the way so its a bit rough. This is A LOT of work and research for me so don't expect anything soon (months). Check it out if you are curious. `server-0.0.5-alpha`
