### ISSUE TITLE
Support for older versions of Android

### ISSUE THREAD

**Issue by Lockszmith** [sethchhim/Kuboo#9]
Amazing app! Truly.

I still own and actually use a Samsung Galaxy Tab Pro 12.2 (model: sm-p905v)
While this is old, it's there only 12" tablet Samsung made, and it's a fantastic format for reading comics.

The kennel it is running is a 3.4.0, making it an API 17 level device.

Samsung will not issue any updates to this tablet.

I wonder whether your application can be made to support this device.

If it's way too much work, then drop it. But if it's doable, I'd love to use it.

Thanks in advance.

**Comment by sethchhim** [comment]
It is indeed too much work for too little pay off. I would need to rewrite a lot and also test everything for backwards compatibility. As of May 7, 2018, API 21 supports 84.7% of Android devices and it will only get better over time.
